version: '3.8'

services:
  server-service:
    build:
      context: ./
      dockerfile: ./Dockerfile-dev
    container_name: server-container
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - FRONTEND=http://127.0.0.1:5500
      - STACK_ENV=test
      - STACK_NAME=resources
